# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  dockerfilepath: '$(Build.SourcesDirectory)/Shopping/Shopping.API/Dockerfile'
  tag: '$(Build.BuildId)'
  imagerepository : 'shoppingapi'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build Docker image
    jobs:
      - job: BuildJob        
        displayName: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: $(imagerepository)
              command: 'buildAndPush'
              Dockerfile: $(dockerfilepath)
              buildContext: $(Build.SourcesDirectory)/Shopping
              
              tags: |
                $(tag)

            
